name: Bug report
description: Report a problem with Battery Lifetime
title: "[Bug]: "
labels: [bug]
body:
  - type: input
    id: version
    attributes:
      label: Battery Lifetime version
      placeholder: 1.0.0
      required: true
  - type: input
    id: home_assistant_version
    attributes:
      label: Home Assistant version
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: Describe the expected and actual behavior.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      render: text
